version: "3.8"

services:
  front_end:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
    networks:
      - auth

  api-rest:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres
    environment:
      - DATABASE=postgres
      - NODE_ENV=production
    ports:
      - "4000:4000"
    networks:
      - auth

  postgres:
    container_name: "postgres_container"
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=pgadmin
      - POSTGRES_PASSWORD=pg123
      - POSTGRES_DB=user_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./backend/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
    networks:
      - auth

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "80:80"
    depends_on:
      - postgres
    networks:
      - auth

volumes:
  postgres-data:

networks:
  auth:
    external: true

